version: '3.3'
services:
  mysql:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'

    volumes:
      - my-db:/var/lib/mysql

    


  nestjs:
    image: nestjs
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  my-db:
